### ISSUE TITLE
Opti Map

### ISSUE THREAD

**Issue by MoliaOnGit** [0xtter/Jurassic-Fight#1]
# TODO:

Reduire le polymorphisme dans map.java

**Comment by 0xtter** [comment]
Hello Quentin, j'ai vu que tu as fait des modifs sur la Map. Le truc c'est que nos parties dépendent de ce code. Ta modification est peut être pertinente, mais je n'ai personnellement pas le temps de repasser sur ma partie pour m'adapter à une action tardive de ta part, donc à moins que tu souhaites reprendre les conflits et les gérer, je vais revert tes commit. Sans réponse de ta part je considèrais que je peux revert tes commits, étant donné que nous n'avons pas le droit d'avoir un message de ta part. Mais ta movitation est la bienvenue, et si tu souhaites contribuer sans interagir ravec nous il reste des parties du projet encore à faire.
